include: package:flutter_lints/flutter.yaml

analyzer:
    exclude:
        - '**/*.g.dart'
        - '**/*.freezed.dart'

    errors:
        invalid_annotation_target: ignore

    language:
        strict-casts: true
        strict-inference: true
        strict-raw-types: true

linter:
    rules:
        # Styling
        - always_declare_return_types
        - always_put_required_named_parameters_first
        - always_use_package_imports
        - avoid_print
        - avoid_redundant_argument_values
        - avoid_returning_null_for_void
        - avoid_types_as_parameter_names
        - prefer_const_constructors
        - prefer_const_declarations
        - prefer_final_fields
        - prefer_final_locals
        - prefer_single_quotes
        - require_trailing_commas
        - sort_child_properties_last
        - unawaited_futures
        - use_key_in_widget_constructors
